const DB="tebakbox-db-v3", STORE="games";
let editingId=null, currentGame=null, peer=null, conn=null, hostSide=false, roomId=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function show(id){["home","editor","host","player"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random()}
function db(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function allGames(){let d=await db();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.updated-a.updated));r.onerror=()=>rej(r.error)})}
async function putGame(g){let d=await db();return new Promise((res,rej)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).put(g);r.onsuccess=()=>res(g);r.onerror=()=>rej(r.error)})}
async function getGame(id){let d=await db();return new Promise((res,rej)=>{let r=d.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function delGame(id){let d=await db();return new Promise((res,rej)=>{let r=d.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function blankGame(){return{id:uid(),name:"Game Baru",updated:Date.now(),levels:Array.from({length:5},(_,i)=>({topic:"",question:"",images:Array(6).fill("")}))}}
function renderLibrary(){allGames().then(gs=>{let el=$("#games");if(!gs.length){el.innerHTML='<div class="empty">Belum ada game.<br>Buat game pertama kamu.</div>';return}el.innerHTML=gs.map(g=>`<div class="card"><div class="cardTop"><div><h3>${esc(g.name)}</h3><div class="muted">5 level • 30 gambar • ${new Date(g.updated).toLocaleDateString("id-ID")}</div></div></div><div class="cardBtns"><button class="primary" onclick="startSaved('${g.id}')">▶ Main</button><button class="ghost" onclick="editSaved('${g.id}')">✏ Edit</button><button class="ghost" onclick="dupSaved('${g.id}')">⧉ Duplikat</button><button class="danger" onclick="removeSaved('${g.id}')">Hapus</button><button class="ghost" onclick="exportSaved('${g.id}')">Export</button></div></div>`).join("")})}
function esc(s){return String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function openEditor(g){editingId=g.id;$("#gameName").value=g.name;$("#editorTitle").textContent=g.name==="Game Baru"?"Buat Game":"Edit Game";let lv=$("#levels");lv.innerHTML=g.levels.map((l,i)=>`<section class="level"><div class="levelHead"><b>LV ${i+1}</b><span class="muted">6 gambar</span></div><div class="levelBody"><label>Topik<input data-topic="${i}" value="${esc(l.topic)}" placeholder="Contoh: Sarapan"></label><label>Pertanyaan<textarea class="question" data-question="${i}" placeholder="Pertanyaan untuk penebak...">${esc(l.question)}</textarea></label><div class="grid">${l.images.map((im,j)=>`<label class="slot"><span class="num">BOX ${j+1}</span>${im?`<img src="${im}">`:"<div class='face'>＋</div>"}<input type="file" accept="image/*" data-img="${i}-${j}"></label>`).join("")}</div></div></section>`).join("");$$("[data-img]").forEach(inp=>inp.addEventListener("change",async e=>{let [i,j]=e.target.dataset.img.split("-").map(Number);let f=e.target.files[0];if(f){g.levels[i].images[j]=await resize(f);g.updated=Date.now();await putGame(readEditor(g));openEditor(await getGame(g.id));toast("Gambar tersimpan");}}));$$("[data-topic], [data-question]").forEach(e=>e.addEventListener("input",()=>{readEditor(g);scheduleSave(g)}));show("editor")}
function readEditor(g){g.name=$("#gameName").value.trim()||"Game Baru";$$("[data-topic]").forEach(e=>g.levels[+e.dataset.topic].topic=e.value);$$("[data-question]").forEach(e=>g.levels[+e.dataset.question].question=e.value);g.updated=Date.now();return g}
let saveTimer;function scheduleSave(g){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{await putGame(g);$("#saveNow").textContent="✓ Auto-saved"},500)}
async function resize(file){return new Promise(res=>{let im=new Image(),r=new FileReader();r.onload=()=>{im.onload=()=>{let max=1200,s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.78))};im.src=r.result};r.readAsDataURL(file)})}
$("#newGame").onclick=async()=>{let g=blankGame();await putGame(g);openEditor(g)}
$("#backHome").onclick=()=>{renderLibrary();show("home")}
$("#saveGame").onclick=async()=>{let g=readEditor(await getGame(editingId));await putGame(g);toast("Game disimpan");renderLibrary();show("home")}
$("#gameName").oninput=()=>{if(editingId)getGame(editingId).then(scheduleSave)}
async function editSaved(id){openEditor(await getGame(id))}
async function startSaved(id){let g=await getGame(id);startHost(g)}
async function dupSaved(id){let g=await getGame(id);g.id=uid();g.name=g.name+" Copy";g.updated=Date.now();await putGame(g);renderLibrary();toast("Game diduplikat")}
async function removeSaved(id){if(confirm("Hapus game ini?")){await delGame(id);renderLibrary();toast("Game dihapus")}}
async function exportSaved(id){let g=await getGame(id),b=new Blob([JSON.stringify(g)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=g.name.replace(/[^\w-]+/g,"_")+".tebakbox";a.click();URL.revokeObjectURL(a.href)}
$("#importBtn").onclick=()=>$("#importFile").click();$("#importFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let g=JSON.parse(await f.text());g.id=uid();g.updated=Date.now();await putGame(g);renderLibrary();toast("Game diimport")}catch{toast("File tidak valid")}};
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startHost(g){hostSide=true;currentGame=JSON.parse(JSON.stringify(g));currentGame.levels.forEach(l=>{l.boxes=shuffle(l.images.map((img,i)=>({id:i,img})))});roomId=null;renderHost();setupPeerHost()}
function setupPeerHost(){peer=new Peer();$("#net").textContent="● CONNECTING";peer.on("open",id=>{roomId=id;$("#net").textContent="● ONLINE";renderHost()});peer.on("connection",c=>{if(conn){c.send({type:"busy"});c.close();return}conn=c;wireHost(c);c.on("open",()=>{c.send({type:"hello",gameName:currentGame.name,level:0});renderHost()})});peer.on("error",e=>{toast("Koneksi gagal");console.log(e)})}
function wireHost(c){c.on("data",m=>{if(m.type==="ping")c.send({type:"pong"});if(m.type==="requestState")sendPublicState()})}
function publicLevel(lv){return{topic:lv.topic,question:lv.question,boxes:lv.boxes.map(x=>({id:x.id}))}}
function sendPublicState(){if(!conn)return;let l=currentGame.levels[currentGame.level];conn.send({type:"state",level:currentGame.level,topic:currentGame.levels[currentGame.level].topic,question:currentGame.levels[currentGame.level].question,boxes:publicLevel(currentGame.levels[currentGame.level]).boxes,opened:currentGame.levels[currentGame.level].boxes.map(x=>x.opened||false),done:currentGame.levels[currentGame.level].boxes.every(x=>x.opened)})}
function renderHost(){show("host");let l=currentGame.levels[currentGame.level||0],idx=currentGame.level||0;$("#host").innerHTML=`<div class="bar"><button class="ghost" onclick="leaveRoom()">← Home</button><div class="pill">HOST • LV ${idx+1}/5</div></div><div class="gameWrap"><div class="eyebrow">${esc(l.topic||"TOPIK")}</div><h1 class="gameTitle">${esc(currentGame.name)}</h1><div class="questionBox"><b>${esc(l.question||"Belum ada pertanyaan")}</b></div><div class="boxes">${l.boxes.map((b,i)=>`<div class="box ${b.opened?"open":""}" onclick="reveal(${i})"><div class="boxInner"><div class="face front">${i+1}</div><div class="face back"><img src="${b.img}"></div></div></div>`).join("")}</div><div class="controls"><button class="primary" onclick="openAll()">Buka Semua</button>${l.boxes.every(b=>b.opened)?(idx<4?`<button class="ghost" onclick="nextLevel()">Lanjut Level ${idx+2}</button>`:`<button class="ghost" onclick="finishGame()">Selesai</button>`):""}</div><div class="status">${conn?"🟢 Penebak sudah terhubung":"🟡 Menunggu penebak..."}</div>${roomId?`<div class="invite">Link Penebak<br>${location.origin+location.pathname+"?room="+roomId}</div><button class="ghost" onclick="copyInvite()">Salin Link</button>`:""}</div>`}
function reveal(i){let l=currentGame.levels[currentGame.level];if(l.boxes[i].opened)return;l.boxes[i].opened=true;renderHost();if(conn)conn.send({type:"reveal",index:i,img:l.boxes[i].img,level:currentGame.level})}
function openAll(){let l=currentGame.levels[currentGame.level];l.boxes.forEach(b=>b.opened=true);renderHost();if(conn)conn.send({type:"revealAll",level:currentGame.level,imgs:l.boxes.map(b=>b.img)})}
function nextLevel(){if(currentGame.level<4){currentGame.level++;renderHost();if(conn)conn.send({type:"next",level:currentGame.level,topic:currentGame.levels[currentGame.level].topic,question:currentGame.levels[currentGame.level].question,boxes:currentGame.levels[currentGame.level].boxes.map(b=>({id:b.id}))})}}
function finishGame(){if(conn)conn.send({type:"finish"});$("#host").innerHTML='<div class="center"><div class="complete">🎉</div><h1>Game Selesai</h1><p class="muted">Semua 5 level sudah dibuka.</p><button class="primary" onclick="leaveRoom()">Kembali ke Library</button></div>'}
function copyInvite(){navigator.clipboard.writeText(location.origin+location.pathname+"?room="+roomId);toast("Link disalin")}
function leaveRoom(){try{conn?.close();peer?.destroy()}catch{}conn=null;peer=null;currentGame=null;renderLibrary();show("home")}
function startPlayer(id){hostSide=false;show("player");$("#player").innerHTML='<div class="center"><div class="complete">🎮</div><h2>Masuk ke Game...</h2><p class="muted">Menghubungkan ke Host</p></div>';peer=new Peer();peer.on("open",()=>{conn=peer.connect(id);conn.on("open",()=>{conn.send({type:"requestState"})});wirePlayer(conn)});peer.on("error",()=>{$("#player").innerHTML='<div class="center"><h2>Room tidak ditemukan</h2><p class="muted">Pastikan Host masih membuka game.</p></div>'})}
function wirePlayer(c){c.on("data",m=>{if(m.type==="busy"){$("#player").innerHTML='<div class="center"><h2>Room penuh</h2><p class="muted">Room ini sudah punya penebak.</p></div>';return}if(m.type==="state")renderPlayer(m);if(m.type==="reveal"){let el=document.querySelector(`[data-box="${m.index}"]`);if(el){el.classList.add("open");el.querySelector("img").src=m.img}}if(m.type==="revealAll")m.imgs.forEach((img,i)=>{let el=document.querySelector(`[data-box="${i}"]`);if(el){el.classList.add("open");el.querySelector("img").src=img}});if(m.type==="next")renderPlayer(m);if(m.type==="finish")$("#player").innerHTML='<div class="center"><div class="complete">🎉</div><h1>Selesai!</h1><p class="muted">Terima kasih sudah bermain.</p></div>'})}
function renderPlayer(m){let boxes=m.boxes||Array.from({length:6},(_,i)=>({id:i}));$("#player").innerHTML=`<div class="gameWrap"><div class="bar"><div class="pill">PENEBak</div><div class="pill">LV ${(m.level||0)+1}/5</div></div><div class="eyebrow">${esc(m.topic||"TOPIK")}</div><h1 class="gameTitle">Tebak!</h1><div class="questionBox"><b>${esc(m.question||"Apa gambar ini?")}</b></div><div class="boxes">${boxes.map((b,i)=>`<div class="box" data-box="${i}"><div class="boxInner"><div class="face front">?</div><div class="face back"><img></div></div></div>`).join("")}</div><div class="playerNote">🎙️ Sebutkan tebakanmu. Host yang membuka box.</div></div>`}
function maybeRoom(){let id=new URLSearchParams(location.search).get("room");if(id)startPlayer(id);else{renderLibrary();show("home")}}
maybeRoom();