const $=s=>document.querySelector(s);
const DB='warungku-data-v3';
const seed={products:[],cart:[],shopping:[],sales:[],profit:0};
let d=JSON.parse(localStorage.getItem(DB)||'null')||seed;
const save=()=>localStorage.setItem(DB,JSON.stringify(d));
if(!Array.isArray(d.products))d.products=[]; if(!Array.isArray(d.shopping))d.shopping=[]; if(!Array.isArray(d.sales))d.sales=[]; if(typeof d.profit!=='number')d.profit=0; save();
const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const p=id=>d.products.find(x=>x.id==id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.className='toast show';clearTimeout(window._toast);window._toast=setTimeout(()=>e.className='toast',1300)}
function home(){const om=d.sales.reduce((s,x)=>s+x.total,0),low=d.products.filter(x=>x.stock<=x.min).length;return `<div class="wrap"><div class="top"><div class="brand"><div class="logo">🏪</div><div><strong>WarungKu</strong><small>Warung + Konter + Agen</small></div></div></div><div class="eyebrow">Dashboard</div><h1 class="title">Selamat datang 👋</h1><p class="muted">Semua kebutuhan usaha dalam satu layar.</p><section class="card hero"><div class="eyebrow">Omzet</div><div class="big">${rp(om)}</div><span class="green">● ${d.sales.length} transaksi</span></section><div class="grid2"><div class="stat"><small>Total Stok</small><b>${d.products.reduce((s,x)=>s+(+x.stock||0),0)}</b></div><div class="stat"><small>Menipis</small><b class="red">${low}</b></div><div class="stat"><small>Laba</small><b class="green">${rp(d.profit)}</b></div><div class="stat"><small>Produk</small><b>${d.products.length}</b></div></div><section class="card"><div class="section"><h2>Aksi Cepat</h2></div><div class="quick"><button onclick="location.hash='kasir'"><b>💰</b>Laba</button><button onclick="location.hash='belanja'"><b>🛒</b>Belanja</button><button onclick="location.hash='stok'"><b>📦</b>Stok</button><button onclick="location.hash='cek'"><b>▣</b>Cek Harga</button><button onclick="location.hash='laporan'"><b>▤</b>Laporan</button><button onclick="location.hash='lainnya'"><b>☰</b>Lainnya</button></div></section></div>`}
function kasir(){return `<div class="wrap"><div class="eyebrow">Keuangan</div><h1 class="title">Input Laba</h1><p class="muted">Catat laba dengan sekali tap.</p><section class="card hero"><div class="eyebrow">Total Laba</div><div class="big">${rp(d.profit)}</div></section><section class="card"><div class="section"><h2>Tambah Cepat</h2><span class="note">Sekali tap</span></div><div class="quick profit-quick"><button onclick="addProfit(2000)"><b>+2K</b><span>Tambah</span></button><button onclick="addProfit(3000)"><b>+3K</b><span>Tambah</span></button><button onclick="addProfit(5000)"><b>+5K</b><span>Tambah</span></button><button onclick="addProfit(10000)"><b>+10K</b><span>Tambah</span></button></div><button class="bigbtn" onclick="manualProfit()">＋ Input Manual</button></section><section class="card"><div class="section"><h2>Catatan</h2><button class="link" onclick="d.profit=0;save();render()">Reset</button></div><p class="note">Tersimpan di HP dan tetap bisa dipakai offline.</p></section></div>`}
function belanja(){const total=d.shopping.length,done=d.shopping.filter(x=>x.done).length;return `<div class="wrap shopping-page"><div class="eyebrow">Catatan Agen</div><h1 class="title">Daftar Belanja</h1><p class="muted">Tulis cepat barang yang mau dibeli. Tidak terhubung ke stok.</p><section class="shopping-note"><div class="note-head"><span>📝 Catatan belanja</span><span>${done}/${total}</span></div><div class="shop-paper">${total?d.shopping.map(x=>`<div class="shop-line ${x.done?'done':''}"><label class="shop-check"><input type="checkbox" ${x.done?'checked':''} onchange="toggleShop(${x.id})"><span></span></label><div class="shop-name">${esc(x.name)}</div><div class="shop-qty">× ${esc(x.qty)}</div><button class="shop-delete" onclick="deleteShop(${x.id})">×</button></div>`).join(''):'<div class="empty-note">Belum ada catatan.<br><span>Tambahkan barang yang mau dibeli ke agen.</span></div>'}</div><button class="add-line" onclick="openShop()">＋ Tambah barang</button></section>${done?`<button class="clear-shop" onclick="clearDoneShop()">Bersihkan yang sudah dibeli</button>`:''}</div>`}
function openShop(){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="sheet"><div class="section"><h2>Tambah ke catatan</h2><button class="link" onclick="this.closest('.modal').remove()">Tutup</button></div><label>Nama barang<input id="shopName" placeholder="contoh: minyak 2L" autocomplete="off"></label><label>Jumlah<input id="shopQty" type="number" min="1" value="1" inputmode="numeric"></label><button class="bigbtn" onclick="addShopManual()">Tambah ke catatan</button></div></div>`);setTimeout(()=>$('#shopName')?.focus(),40)}
function addShopManual(){const name=$('#shopName')?.value.trim(),qty=Math.max(1,parseInt($('#shopQty')?.value,10)||1);if(!name)return;d.shopping.push({id:Date.now()+Math.random(),name,qty,done:false});save();document.querySelector('.modal')?.remove();render()}
function toggleShop(id){const x=d.shopping.find(x=>x.id==id);if(x){x.done=!x.done;save();render()}}
function deleteShop(id){d.shopping=d.shopping.filter(x=>x.id!=id);save();render()}
function clearDoneShop(){d.shopping=d.shopping.filter(x=>!x.done);save();render()}
function stok(){const low=d.products.filter(x=>x.stock<=x.min);return `<div class="wrap"><div class="eyebrow">Inventori</div><h1 class="title">Stok Barang</h1><div class="stock-actions"><button class="bigbtn" onclick="openProduct()">＋ Tambah Barang</button><button class="scan-btn" onclick="scanFor('add')">▣ Scan Barcode</button></div><p class="note">Scan barcode untuk mengambil nama produk otomatis. Kalau salah, nama tetap bisa diedit manual.</p><div class="search"><input id="sq" placeholder="Cari nama atau barcode..." oninput="sstock()"></div><div class="grid2"><div class="stat"><small>Total Stok</small><b>${d.products.reduce((s,x)=>s+(+x.stock||0),0)}</b></div><div class="stat"><small>Produk</small><b>${d.products.length}</b></div></div><section class="card" id="slist">${stockCards(d.products)}</section></div>`}
function stockCards(a){return a.length?a.map(x=>`<div class="stock-card"><div class="product"><div class="pic">${esc(x.icon||'📦')}</div><main><b>${esc(x.name)}</b><small>${esc(x.barcode||'Tanpa barcode')} · Modal ${rp(x.buy)} · Jual ${rp(x.sell)}</small></main><div class="stock-num"><b class="${x.stock<=x.min?'red':'green'}">${x.stock}</b><small>stok</small></div></div><div class="stock-actions-row"><button onclick="openProduct(${x.id})">Edit</button><button onclick="scanFor('price',${x.id})">Scan</button><button onclick="deleteProduct(${x.id})">Hapus</button></div></div>`).join(''):'<div class="empty-note">Belum ada barang.<br><span>Tambahkan lewat scan barcode atau manual.</span></div>'}
function sstock(){const q=($('#sq')?.value||'').toLowerCase();$('#slist').innerHTML=stockCards(d.products.filter(x=>x.name.toLowerCase().includes(q)||String(x.barcode||'').includes(q)))}
function openProduct(id=null,barcode=''){const x=id?p(id):null;document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="sheet"><div class="section"><h2>${x?'Edit Barang':'Tambah Barang'}</h2><button class="link" onclick="this.closest('.modal').remove()">Tutup</button></div><label>Barcode<input id="prodBarcode" value="${esc(x?.barcode||barcode)}" inputmode="numeric" placeholder="Scan atau ketik barcode"></label><div class="inline"><label>Nama barang<input id="prodName" value="${esc(x?.name||'')}" placeholder="Nama produk"></label><button class="mini-scan" onclick="scanFor('fill')">▣</button></div><label>Jumlah stok<input id="prodStock" type="number" min="0" value="${x?.stock??0}" inputmode="numeric"></label><div class="inline2"><label>Harga modal<input id="prodBuy" type="number" min="0" value="${x?.buy??0}" inputmode="numeric"></label><label>Harga jual<input id="prodSell" type="number" min="0" value="${x?.sell??0}" inputmode="numeric"></label></div><label>Batas stok minimum<input id="prodMin" type="number" min="0" value="${x?.min??2}" inputmode="numeric"></label><button class="bigbtn" onclick="saveProduct(${id||'null'})">Simpan Barang</button></div></div>`);setTimeout(()=>$('#prodName')?.focus(),40)}
async function saveProduct(id){const name=$('#prodName').value.trim();if(!name)return toast('Nama barang belum diisi');const item={id:id||Date.now(),name,barcode:$('#prodBarcode').value.trim(),stock:+$('#prodStock').value||0,buy:+$('#prodBuy').value||0,sell:+$('#prodSell').value||0,min:+$('#prodMin').value||0,cat:'Umum',icon:'📦'};if(id){const i=d.products.findIndex(x=>x.id==id);if(i>=0)d.products[i]={...d.products[i],...item}}else d.products.unshift(item);save();document.querySelector('.modal')?.remove();render()}
function deleteProduct(id){if(confirm('Hapus barang ini?')){d.products=d.products.filter(x=>x.id!=id);save();render()}}
function cek(){return `<div class="wrap"><div class="eyebrow">Kasir</div><h1 class="title">Cek Harga</h1><p class="muted">Scan barang saat pembeli bertanya harga.</p><section class="price-check"><div class="price-icon">▣</div><h2>Scan Barcode</h2><p>Barang yang sudah tersimpan akan langsung menampilkan harga jual.</p><button class="bigbtn" onclick="scanFor('price')">▣ Scan & Cek Harga</button><div class="manual-barcode"><input id="manualCode" inputmode="numeric" placeholder="Atau ketik barcode"><button onclick="lookupPrice($('#manualCode').value.trim())">Cek</button></div></section></div>`}
function lookupPrice(code){const x=d.products.find(x=>String(x.barcode||'')===String(code));if(!x)return showPrice(null,code);showPrice(x)}
function showPrice(x,code=''){document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="sheet price-sheet"><div class="price-icon">${x?'✓':'?'}</div><h2>${x?esc(x.name):'Barcode belum terdaftar'}</h2>${x?`<div class="price-big">${rp(x.sell)}</div><p class="note">Modal ${rp(x.buy)} · Stok ${x.stock}</p>`:`<p class="note">${esc(code)} belum ada di stok. Kamu bisa langsung menambahkannya.</p><button class="bigbtn" onclick="this.closest('.modal').remove();openProduct(null,'${esc(code)}')">＋ Tambah Barang</button>`}<button class="dark close-price" onclick="this.closest('.modal').remove()">Tutup</button></div></div>`)}
async function scanFor(mode,id=null){if(!('BarcodeDetector' in window)){const code=prompt('Scanner kamera belum didukung browser ini. Masukkan barcode:');if(code)await handleBarcode(code,mode,id);return}const formats=['ean_13','ean_8','upc_a','upc_e','code_128'];let detector;try{detector=new BarcodeDetector({formats})}catch{detector=new BarcodeDetector()}const modal=document.createElement('div');modal.className='scanner';modal.innerHTML=`<div class="scanner-box"><div class="section"><h2>Scan Barcode</h2><button class="link" id="closeScan">Tutup</button></div><video autoplay playsinline></video><p class="note">Arahkan barcode ke kamera.</p></div>`;document.body.appendChild(modal);const video=modal.querySelector('video');let stream;const close=()=>{stream?.getTracks().forEach(t=>t.stop());modal.remove()};modal.querySelector('#closeScan').onclick=close;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});video.srcObject=stream;await video.play();let busy=false;const loop=async()=>{if(!document.body.contains(modal)||busy)return;if(video.readyState>=2){try{const codes=await detector.detect(video);if(codes.length){busy=true;const code=codes[0].rawValue;close();await handleBarcode(code,mode,id);return}}catch{}}requestAnimationFrame(loop)};loop()}catch{close();toast('Kamera tidak bisa dibuka') }}
async function handleBarcode(code,mode,id){if(mode==='price'){const x=d.products.find(x=>String(x.barcode||'')===String(code));if(x)showPrice(x,code);else{try{const info=await lookupOnline(code);if(info)showPrice({...info,stock:'—'},code);else showPrice(null,code)}catch{showPrice(null,code)} }return}if(mode==='fill'){const info=await lookupOnline(code);$('#prodBarcode').value=code;if(info&&!$('#prodName').value)$('#prodName').value=info.name||'';if(info?.icon){}return}if(mode==='add'){const x=d.products.find(x=>String(x.barcode||'')===String(code));if(x){openProduct(x.id);return}const info=await lookupOnline(code);openProduct(null,code);if(info){setTimeout(()=>{if(info.name)$('#prodName').value=info.name},30)}}}
async function lookupOnline(code){try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`,{headers:{Accept:'application/json'}});if(!r.ok)return null;const j=await r.json();if(j.status!==1)return null;return{name:j.product?.product_name||j.product?.generic_name||'',icon:'📦'}}catch{return null}}
function addProfit(n){d.profit+=n;save();render()}
function manualProfit(){const n=prompt('Nominal laba:');if(n&&!isNaN(+n))addProfit(+n)}
function laporan(){const om=d.sales.reduce((s,x)=>s+x.total,0);return `<div class="wrap"><div class="eyebrow">Analitik</div><h1 class="title">Laporan</h1><div class="grid2"><div class="stat"><small>Penjualan</small><b>${rp(om)}</b></div><div class="stat"><small>Laba</small><b class="green">${rp(d.profit)}</b></div></div><section class="card"><h2>${d.sales.length} transaksi</h2><p class="note">Data tersimpan lokal di perangkat.</p></section></div>`}
function lainnya(){return `<div class="wrap"><div class="eyebrow">Pengaturan</div><h1 class="title">Lainnya</h1><section class="card"><div class="section"><div><b>Mode Offline</b><div class="note">Data lokal + cache aplikasi</div></div><b class="green">AKTIF</b></div></section><section class="card"><button id="install" class="bigbtn" style="display:${deferred?'block':'none'}">＋ Instal Aplikasi</button><p class="note">Instal sebagai aplikasi PWA, bukan bookmark.</p></section><section class="card"><button class="dark" style="width:100%" onclick="if(confirm('Hapus semua data?')){localStorage.removeItem(DB);location.reload()}">Reset Data</button></section></div>`}
let deferred=null;
function render(){const r=location.hash.slice(1)||'home';const f={home,kasir,belanja,stok,cek,laporan,lainnya}[r]||home;$('#app').innerHTML=f();document.querySelectorAll('.bottom a').forEach(a=>a.classList.toggle('active',a.dataset.tab===r));if($('#install'))$('#install').onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;render()}}
window.addEventListener('hashchange',render);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;render()});window.addEventListener('appinstalled',()=>{deferred=null});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(()=>{});
render();
